#!/bin/bash
chmod +x .git/hooks/post-checkout
current_branch=$(git rev-parse --abbrev-ref HEAD)

if [ "$current_branch" == "partie-2" ]; then
    # Authenticate with GitHub using gh
    echo "Authenticating with GitHub..."
    gh auth login --web

    gh pr create --base "main" --head "partie-2" --title "Partie 2 - Revue de code" --body "Partie 2"
fi
